### ISSUE TITLE
niftyperforce failed to load when "auto checkout projects" is enabled 

### ISSUE THREAD

**Issue by vaderr12** [belkiss/niftyplugins#15]
when I've enabled "auto checkout projects" in niftyperforce settings, VS 2020 restarted and window show up with message that extension didn't load properly. Log bellow:

NiftyPerforce ( Info): NiftyPerforce v3.0.0 compiled on 18.11.2021 10:59:56
NiftyPerforce ( Info):     Adding handlers to automatically add files to perforce as you add them to the project
NiftyPerforce ( Info):     Adding handlers for automatically checking out .vcproj files when you do changes to the project
NiftyPerforce ( Warn):     Failed to register OnCheckoutSelectedProjects to command 'ClassViewContextMenus.ClassViewProject.Properties'

**Comment by belkiss** [comment]
Heya! Thanks for the report, I can confirm and repro the issue, I'll fix it asap!

I never use this feature so never noticed... but pretty sure that AutoCheckoutOnSave will check-out the project files (vcxproj/csproj/etc.) if they were modified on save/save all/build.

**Comment by belkiss** [comment]
Fixed with a6a3d65cba48c12fdd13f5d02cbaf697486d0032 and released in version 
https://github.com/belkiss/niftyplugins/releases/tag/3.0.1

**Comment by vaderr12** [comment]
thanks
